safe: false
port: 4000
highlighter: rouge
future: false
timezone: Europe/Moscow
lsi: false
markdown: kramdown
syntax_highlighter: rouge
highlighter: rouge
baseurl: ""

source: src
destination: build

permalink: /:categories/:title
name: HappyJedi's blog
author: Victor Vinogradov
description: Victor Vinogradov - a software developer, entrepreneur and traveller
email: 'happy.jedi.g@gmail.com'
url: 'http://happyjedi.pro'
twitter_username: HappyJedi
linkedin: https://www.linkedin.com/in/vinogradovvictor/
facebook: https://www.facebook.com/profile.php?id=100011351259791
github_user: happyjedi
skype: happy.jedi.v
upwork: https://www.upwork.com/o/profiles/users/_~012e21489bc1a0781d/
telegram: https://t.me/HappyJedi

opengraph:
  page: https://www.facebook.com/profile.php?id=100011351259791
  personal: https://www.facebook.com/profile.php?id=100011351259791
  image: apple-touch-icon

header: Mars_1920x1200
time: 2017-07-22

static_path: 'http://happyjedi.pro/assets/'
styles_path: 'http://happyjedi.pro/assets/'
scripts_path: 'http://happyjedi.pro/assets/'

imgix:
  main_images: http://happyjedi.pro/assets/
  metadata_images: http://happyjedi.pro/assets/

jekyll-archives:
  layouts:
    tag: tag
  enabled:
    - tags
  permalinks:
    tag: /tag/:name/

pagination:
  limit: false
  per_page: 12
  permalink: /:num/index.html

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - readme.md
  - .gitlab-ci.yml
  - .gitignore
  - vendor
  - Procile
  - config.ru
  - .asset-cache

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-archives
  - jekyll-assets
  - jekyll-sitemap
  - rouge
  - jekyll-redirect-from
  - octopress-paginate
  - jekyll-newrelic

#assets:
#  sources:
#    - _scripts
#    - _styles
#  js_compressor: yui
#  css_compressor: yui
#  debug: false
#  baseurl: http://happyjedi.pro

assets:
  autowrite: true
  prefix: "/assets"
  digest: false
  assets:
    - "*.jpg"
    - "*.png"
    - "*.ico"
    - "*.pdf"
  sources:
    - _assets/css
    - _assets/fonts
    - _assets/images
    - _assets/files
#    - _assets/images/development
#    - _assets/images/notes
#    - _assets/images/travels
    - _assets/js
    - _assets
    - ..

  js_compressor: yui
  css_compressor: yui
  debug: false
  baseurl: http://happyjedi.pro

defaults:
  - scope:
      path: ''
    values:
      footer_related_posts: false
      comments: false

  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
      is_page: true
      is_post: false
      footer_related_posts: false
      comments: false


  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      banner_position: 'middle'
      is_page: false
      is_post: true
      comments: true
      footer_related_posts: true

# Collections

collections:
   projects:
     output: true

mapbox:
  options:
    zoompan: true
    zoomwheel: false
    geocoder: false
    link: false
  id_prefix: happyjedi.
  access_token: pk.eyJ1IjoiaGFwcHlqZWRpIiwiYSI6ImNqNWZsbmxodTBoejEycG8xNmpybDJrdm8ifQ.BEBjJ6bmSZ3HPjKP1suprA

newrelic:
  licenseKey: "c4cce08607"
  applicationID: "60959481"