safe: false
port: 4000
highlighter: rouge
future: false
timezone: Europe/Moscow
lsi: false
markdown: kramdown

source: src
destination: build

permalink: /:categories/:year/:month/:title
name: Victor Vinogradov Software developer
description: "I'm a software developer, entrepreneur and traveller"
email: 'happy.jedi.g@gmail.com'
url: 'http://happyjedi.pro'

opengraph:
  page: https://www.facebook.com/profile.php?id=100011351259791
  personal: https://www.facebook.com/profile.php?id=100011351259791
  image: jedi

header: Mars_1920x1200
time: 2017-07-22

static_path: 'http://happyjedi.pro/assets/'
styles_path: 'http://happyjedi.pro/assets/'
scripts_path: 'http://happyjedi.pro/assets/'

imgix:
  main_images: http://happyjedi.pro/assets/
  metadata_images: http://happyjedi.pro/assets/

jekyll-archives:
  layouts:
    tag: tag
  enabled:
    - tags
  permalinks:
    tag: /tag/:name/

pagination:
  limit: false
  per_page: 12
  permalink: /:num/index.html

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - readme.md
  - .gitlab-ci.yml
  - .gitignore
  - vendor
  - Procile
  - config.ru

kramdown:
  parse_span_html: false
  parse_block_html: false

plugins:
  - bourbon
  - neat
  - jekyll-assets
  - jekyll-archives
  - jekyll-sitemap
  - rouge
  - jekyll-redirect-from
  - octopress-paginate
  - jekyll-newrelic

assets:
  sources:
    - _scripts
    - _styles
  js_compressor: yui
  css_compressor: yui
  debug: false
  baseurl: http://happyjedi.pro

defaults:
  - scope:
      path: ''
    values:
      footer_related_posts: true
      comments: false

  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'main'
      is_page: true
      is_post: false

  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'default'
      banner_position: 'middle'
      is_page: false
      is_post: true

mapbox:
  options:
    zoompan: true
    zoomwheel: false
    geocoder: false
    link: false
  id_prefix: happyjedi.
  access_token: pk.eyJ1IjoiaGFwcHlqZWRpIiwiYSI6ImNqNWZsbmxodTBoejEycG8xNmpybDJrdm8ifQ.BEBjJ6bmSZ3HPjKP1suprA

newrelic:
  licenseKey: "c4cce08607"
  applicationID: "60959481"